"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from agentset.types import BaseModel, UNSET_SENTINEL
from agentset.utils import FieldMetadata, PathParamMetadata, validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetFileDownloadURLGlobalsTypedDict(TypedDict):
    namespace_id: NotRequired[str]
    r"""The id of the namespace (prefixed with ns_)"""


class GetFileDownloadURLGlobals(BaseModel):
    namespace_id: Annotated[
        Optional[str],
        pydantic.Field(alias="namespaceId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""The id of the namespace (prefixed with ns_)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["namespaceId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetFileDownloadURLRequestTypedDict(TypedDict):
    document_id: str
    r"""The id of the document (prefixed with doc_)"""


class GetFileDownloadURLRequest(BaseModel):
    document_id: Annotated[
        str,
        pydantic.Field(alias="documentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The id of the document (prefixed with doc_)"""


class GetFileDownloadURLDataTypedDict(TypedDict):
    url: str


class GetFileDownloadURLData(BaseModel):
    url: str


class GetFileDownloadURLResponseTypedDict(TypedDict):
    r"""The presigned download URL for the file"""

    data: GetFileDownloadURLDataTypedDict
    success: Literal[True]


class GetFileDownloadURLResponse(BaseModel):
    r"""The presigned download URL for the file"""

    data: GetFileDownloadURLData

    SUCCESS: Annotated[
        Annotated[Literal[True], AfterValidator(validate_const(True))],
        pydantic.Field(alias="success"),
    ] = True


try:
    GetFileDownloadURLResponse.model_rebuild()
except NameError:
    pass
