"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from agentset.types import BaseModel, Nullable, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Any, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class HostingTypedDict(TypedDict):
    namespace_id: str
    r"""The ID of the namespace this hosting belongs to."""
    title: Nullable[str]
    r"""The title displayed on the hosted interface."""
    slug: Nullable[str]
    r"""The unique slug for accessing the hosted interface."""
    logo: Nullable[str]
    r"""The URL or base64 encoded image of the logo."""
    og_title: Nullable[str]
    r"""Custom Open Graph title for social media sharing."""
    og_description: Nullable[str]
    r"""Custom Open Graph description for social media sharing."""
    og_image: Nullable[str]
    r"""Custom Open Graph image URL for social media sharing."""
    system_prompt: Nullable[str]
    r"""The system prompt used for the chat interface."""
    example_questions: List[str]
    r"""Example questions to display to users in the chat interface."""
    example_search_queries: List[str]
    r"""Example search queries to display to users in the search interface."""
    welcome_message: Nullable[str]
    r"""Welcome message displayed to users."""
    citation_metadata_path: Nullable[str]
    r"""Path to metadata field used for citations."""
    rerank_config: Any
    r"""Configuration for the reranking model."""
    llm_config: Any
    r"""Configuration for the LLM model."""
    allowed_emails: List[str]
    r"""List of allowed email addresses (when protected is true)."""
    allowed_email_domains: List[str]
    r"""List of allowed email domains (when protected is true)."""
    created_at: str
    r"""The date and time the hosting was created."""
    updated_at: str
    r"""The date and time the hosting was last updated."""
    search_enabled: NotRequired[bool]
    r"""Whether search functionality is enabled."""
    top_k: NotRequired[int]
    r"""Number of documents to retrieve from vector store."""
    protected: NotRequired[bool]
    r"""Whether the hosted interface is protected by authentication."""


class Hosting(BaseModel):
    namespace_id: Annotated[str, pydantic.Field(alias="namespaceId")]
    r"""The ID of the namespace this hosting belongs to."""

    title: Nullable[str]
    r"""The title displayed on the hosted interface."""

    slug: Nullable[str]
    r"""The unique slug for accessing the hosted interface."""

    logo: Nullable[str]
    r"""The URL or base64 encoded image of the logo."""

    og_title: Annotated[Nullable[str], pydantic.Field(alias="ogTitle")]
    r"""Custom Open Graph title for social media sharing."""

    og_description: Annotated[Nullable[str], pydantic.Field(alias="ogDescription")]
    r"""Custom Open Graph description for social media sharing."""

    og_image: Annotated[Nullable[str], pydantic.Field(alias="ogImage")]
    r"""Custom Open Graph image URL for social media sharing."""

    system_prompt: Annotated[Nullable[str], pydantic.Field(alias="systemPrompt")]
    r"""The system prompt used for the chat interface."""

    example_questions: Annotated[List[str], pydantic.Field(alias="exampleQuestions")]
    r"""Example questions to display to users in the chat interface."""

    example_search_queries: Annotated[
        List[str], pydantic.Field(alias="exampleSearchQueries")
    ]
    r"""Example search queries to display to users in the search interface."""

    welcome_message: Annotated[Nullable[str], pydantic.Field(alias="welcomeMessage")]
    r"""Welcome message displayed to users."""

    citation_metadata_path: Annotated[
        Nullable[str], pydantic.Field(alias="citationMetadataPath")
    ]
    r"""Path to metadata field used for citations."""

    rerank_config: Annotated[Any, pydantic.Field(alias="rerankConfig")]
    r"""Configuration for the reranking model."""

    llm_config: Annotated[Any, pydantic.Field(alias="llmConfig")]
    r"""Configuration for the LLM model."""

    allowed_emails: Annotated[List[str], pydantic.Field(alias="allowedEmails")]
    r"""List of allowed email addresses (when protected is true)."""

    allowed_email_domains: Annotated[
        List[str], pydantic.Field(alias="allowedEmailDomains")
    ]
    r"""List of allowed email domains (when protected is true)."""

    created_at: Annotated[str, pydantic.Field(alias="createdAt")]
    r"""The date and time the hosting was created."""

    updated_at: Annotated[str, pydantic.Field(alias="updatedAt")]
    r"""The date and time the hosting was last updated."""

    search_enabled: Annotated[Optional[bool], pydantic.Field(alias="searchEnabled")] = (
        True
    )
    r"""Whether search functionality is enabled."""

    top_k: Annotated[Optional[int], pydantic.Field(alias="topK")] = 50
    r"""Number of documents to retrieve from vector store."""

    protected: Optional[bool] = True
    r"""Whether the hosted interface is protected by authentication."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["searchEnabled", "topK", "protected"])
        nullable_fields = set(
            [
                "title",
                "slug",
                "logo",
                "ogTitle",
                "ogDescription",
                "ogImage",
                "systemPrompt",
                "welcomeMessage",
                "citationMetadataPath",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
