"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .batch_payload import BatchPayload, BatchPayloadTypedDict
from .file_payloadoutput import FilePayloadOutput, FilePayloadOutputTypedDict
from .managed_file_payloadoutput import (
    ManagedFilePayloadOutput,
    ManagedFilePayloadOutputTypedDict,
)
from .text_payload import TextPayload, TextPayloadTypedDict
from agentset.utils import get_discriminator
from pydantic import Discriminator, Tag
from typing import Union
from typing_extensions import Annotated, TypeAliasType


IngestJobPayloadTypedDict = TypeAliasType(
    "IngestJobPayloadTypedDict",
    Union[
        BatchPayloadTypedDict,
        TextPayloadTypedDict,
        FilePayloadOutputTypedDict,
        ManagedFilePayloadOutputTypedDict,
    ],
)
r"""The ingest job payload."""


IngestJobPayload = Annotated[
    Union[
        Annotated[TextPayload, Tag("TEXT")],
        Annotated[FilePayloadOutput, Tag("FILE")],
        Annotated[ManagedFilePayloadOutput, Tag("MANAGED_FILE")],
        Annotated[BatchPayload, Tag("BATCH")],
    ],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]
r"""The ingest job payload."""
