"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .ingest_job_status import IngestJobStatus
from agentset.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from agentset.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class IngestJobWebhookEventDataTypedDict(TypedDict):
    id: str
    r"""Unique identifier for the ingest job."""
    name: Nullable[str]
    r"""Name of the ingest job."""
    namespace_id: str
    r"""ID of the namespace."""
    organization_id: str
    r"""ID of the organization."""
    status: IngestJobStatus
    r"""The status of the ingest job."""
    created_at: str
    r"""When the ingest job was created."""
    updated_at: str
    r"""When the ingest job was last updated."""
    error: NotRequired[Nullable[str]]
    r"""Error message if ingest job failed."""


class IngestJobWebhookEventData(BaseModel):
    id: str
    r"""Unique identifier for the ingest job."""

    name: Nullable[str]
    r"""Name of the ingest job."""

    namespace_id: Annotated[str, pydantic.Field(alias="namespaceId")]
    r"""ID of the namespace."""

    organization_id: Annotated[str, pydantic.Field(alias="organizationId")]
    r"""ID of the organization."""

    status: IngestJobStatus
    r"""The status of the ingest job."""

    created_at: Annotated[str, pydantic.Field(alias="createdAt")]
    r"""When the ingest job was created."""

    updated_at: Annotated[str, pydantic.Field(alias="updatedAt")]
    r"""When the ingest job was last updated."""

    error: OptionalNullable[str] = UNSET
    r"""Error message if ingest job failed."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["error"])
        nullable_fields = set(["name", "error"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class IngestJobWebhookEventTypedDict(TypedDict):
    r"""Triggered when an ingest job is queued, processed, ready, or deleted."""

    id: str
    created_at: str
    data: IngestJobWebhookEventDataTypedDict
    event: Literal["ingest_job.queued"]


class IngestJobWebhookEvent(BaseModel):
    r"""Triggered when an ingest job is queued, processed, ready, or deleted."""

    id: str

    created_at: Annotated[str, pydantic.Field(alias="createdAt")]

    data: IngestJobWebhookEventData

    EVENT: Annotated[
        Annotated[
            Literal["ingest_job.queued"],
            AfterValidator(validate_const("ingest_job.queued")),
        ],
        pydantic.Field(alias="event"),
    ] = "ingest_job.queued"
