"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .documentwebhookevent import DocumentWebhookEvent, DocumentWebhookEventTypedDict
from .ingestjobwebhookevent import IngestJobWebhookEvent, IngestJobWebhookEventTypedDict
from agentset.utils import get_discriminator
from pydantic import Discriminator, Tag
from typing import Union
from typing_extensions import Annotated, TypeAliasType


WebhookEventTypedDict = TypeAliasType(
    "WebhookEventTypedDict",
    Union[DocumentWebhookEventTypedDict, IngestJobWebhookEventTypedDict],
)
r"""Webhook event schema"""


WebhookEvent = Annotated[
    Union[
        Annotated[DocumentWebhookEvent, Tag("document.queued")],
        Annotated[IngestJobWebhookEvent, Tag("ingest_job.queued")],
    ],
    Discriminator(lambda m: get_discriminator(m, "event", "event")),
]
r"""Webhook event schema"""
