"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .agentseterror import AgentsetError
from typing import Any, TYPE_CHECKING

from agentset.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .agentsetdefaulterror import AgentsetDefaultError
    from .badrequest_error import BadRequestError, BadRequestErrorData
    from .conflict_error import ConflictError, ConflictErrorData
    from .forbidden_error import ForbiddenError, ForbiddenErrorData
    from .internalservererror import InternalServerError, InternalServerErrorData
    from .inviteexpired_error import InviteExpiredError, InviteExpiredErrorData
    from .no_response_error import NoResponseError
    from .notfound_error import NotFoundError, NotFoundErrorData
    from .ratelimitexceeded_error import (
        RateLimitExceededError,
        RateLimitExceededErrorData,
    )
    from .responsevalidationerror import ResponseValidationError
    from .unauthorized_error import UnauthorizedError, UnauthorizedErrorData
    from .unprocessableentity_error import (
        UnprocessableEntityError,
        UnprocessableEntityErrorData,
    )

__all__ = [
    "AgentsetDefaultError",
    "AgentsetError",
    "BadRequestError",
    "BadRequestErrorData",
    "ConflictError",
    "ConflictErrorData",
    "ForbiddenError",
    "ForbiddenErrorData",
    "InternalServerError",
    "InternalServerErrorData",
    "InviteExpiredError",
    "InviteExpiredErrorData",
    "NoResponseError",
    "NotFoundError",
    "NotFoundErrorData",
    "RateLimitExceededError",
    "RateLimitExceededErrorData",
    "ResponseValidationError",
    "UnauthorizedError",
    "UnauthorizedErrorData",
    "UnprocessableEntityError",
    "UnprocessableEntityErrorData",
]

_dynamic_imports: dict[str, str] = {
    "AgentsetDefaultError": ".agentsetdefaulterror",
    "BadRequestError": ".badrequest_error",
    "BadRequestErrorData": ".badrequest_error",
    "ConflictError": ".conflict_error",
    "ConflictErrorData": ".conflict_error",
    "ForbiddenError": ".forbidden_error",
    "ForbiddenErrorData": ".forbidden_error",
    "InternalServerError": ".internalservererror",
    "InternalServerErrorData": ".internalservererror",
    "InviteExpiredError": ".inviteexpired_error",
    "InviteExpiredErrorData": ".inviteexpired_error",
    "NoResponseError": ".no_response_error",
    "NotFoundError": ".notfound_error",
    "NotFoundErrorData": ".notfound_error",
    "RateLimitExceededError": ".ratelimitexceeded_error",
    "RateLimitExceededErrorData": ".ratelimitexceeded_error",
    "ResponseValidationError": ".responsevalidationerror",
    "UnauthorizedError": ".unauthorized_error",
    "UnauthorizedErrorData": ".unauthorized_error",
    "UnprocessableEntityError": ".unprocessableentity_error",
    "UnprocessableEntityErrorData": ".unprocessableentity_error",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
